# -*- coding: utf-8 -*-
"""Notes Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LhmcuJal6y1ega12ARBRhFZYFmRBCiTE
"""

!pip install transformers

from transformers import pipeline
#Load text generation model
note_generator=pipeline(
    'text-generation',
    model='gpt2'
)
#Take chapter name from user
chapter = input("Enter Chapter Name:")
#----------Detailed Notes--------------
prompt_notes=f"""
Write detailed study notes for the chapter:
{chapter}
Include explanation, examples, and key points.
"""
detailed_notes=note_generator(
    prompt_notes,
    max_length=300,
    num_return_sequences=1
    )
print("\n Detailed Notes:\n")
print(detailed_notes[0]['generated_text'])
#---------One Page Summary---------
prompt_summary=f"""
Summarize the chapter {chapter} into one page.
Make it simple and exam-oriented.
"""
summary=note_generator(
    prompt_summary,
    max_length=200,
    num_return_sequences=1
)
print("\n ONE PAGE SUMMARY:\n")
print(summary[0]['generated_text'])
#--------Definitions & Formula--------
prompt_definition = f"""
List important definitions and formulas for the chapter:
{chapter}
Use bullet points.
"""
definitions=note_generator(
    prompt_definition,
    max_length=200,
    num_return_sequences=1
)
print("\n DEFINITIONS & FORMULAS:\n")
print(definitions[0]['generated_text'])

