# -*- coding: utf-8 -*-
"""Sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eHXtDeHsdxIQK5b183fLoSz6gqJXxo9i
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
#Load the model
model = SentenceTransformer('all-MiniLM-L6-v2')
#take input from user
text1=input("Enter the text 1: ")
text2=input("Enter the text 2: ")
#convert text to embeddingsing1,embedding2)
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculate similarity
similarity=util.cos_sim(embedding1,embedding2)
print("Similarity between the 2 texts is: ", round(float(similarity),2))
if(similarity>0.75):
   print("the similarity level is: Max")
elif(similarity>0.4):
     print("the similarity level is: Medium")
else:
   print("the similarity level is: Low")

