# -*- coding: utf-8 -*-
"""Text Generation Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKcRvp20iZ1zeOFTsnGLZqUSVSRjZTe6
"""

!pip install transformers torch

from transformers import pipeline
#Load text generation model (GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
    )
#input code
prompt = "Artificial Intelligence in finance will"
#generate text
result=generator(prompt,max_length=50,num_return_sequences=1)

print("AI Generated Text")
print(result[0]['generated_text'])

